// projectsData.js
//import getProjectImages from './components/portfolio/getProjectImages';

const projects_ENG = [
  // ========== NEW AI/BLOCKCHAIN PROJECTS ==========
  
  // 1. Intelligent RAG System
  {
    id: "rag-system",
    folderid: "rag-system",
    projectType: "web",
    platforme: "Full-Stack Web Application",
    title: "Intelligent RAG System for Math Education",
    //image: getProjectImages('rag-system'),
    category: "AI & Education",
    date: "2024",
    client_for: "Academic Project",
    role: "Full-Stack AI Developer",
    description: "An intelligent Retrieval-Augmented Generation system that helps students find and understand math exercises. Features web scraping, AI-powered explanations, semantic search, and a modern web interface.",
    github_link: "https://github.com/NizarBelaatik/RAG_Math_College",
    live_demo: "#",
    
    technology: ["Python", "FastAPI", "React", "FAISS", "HuggingFace", "OpenRouter API"],
    technology_used: {
      'front_end': ["React", "Tailwind CSS", "JavaScript"],
      'back_end': ["Python", "FastAPI", "LangChain"],
      'ai_ml': ["HuggingFace Embeddings", "FAISS", "OpenRouter API"],
      'database': ['JSONL', "Vector Database"],
      'tools': ['Selenium', 'BeautifulSoup', 'pdfplumber']
    },
    
    RoleResp: [{
      Title_1: "Full-Stack AI Developer",
      Data: [
        {
          Title: "Data Pipeline Development",
          Data: [
            "Built web scraping system to extract math exercises from AlloSchool",
            "Implemented PDF processing and text extraction pipeline",
            "Created AI enrichment system using OpenRouter API for step-by-step explanations"
          ]
        },
        {
          Title: "RAG System Architecture",
          Data: [
            "Designed vector search system with FAISS and HuggingFace embeddings",
            "Implemented semantic search backend with FastAPI",
            "Built React frontend with real-time chat interface"
          ]
        },
        {
          Title: "AI Integration",
          Data: [
            "Integrated multiple AI models for content generation and enrichment",
            "Implemented caching and optimization for API calls",
            "Developed prompt engineering for educational content"
          ]
        }
      ],
    }],
    
    KeyFeatures: [{
      Title_1: null,
      Data: [
        {
          Title: "Intelligent Search & Retrieval",
          Data: [
            "Semantic search across 1,500+ math exercises",
            "FAISS vector database for fast similarity search",
            "Multilingual embeddings for French/Arabic content"
          ]
        },
        {
          Title: "AI-Powered Explanations",
          Data: [
            "Step-by-step solutions generated by AI",
            "Automatic correction for missing answers",
            "Contextual explanations based on student queries"
          ]
        },
        {
          Title: "Modern Web Interface",
          Data: [
            "Real-time chat interface with response navigation",
            "Responsive design with Tailwind CSS",
            "Multiple answer regeneration and filtering"
          ]
        }
      ],
    }],
    
    VisualsMedia: {
      ScreenShot: [
        { 
          image: ['rag-dashboard.png'],
          info: ['Main dashboard showing search interface and chat functionality']
        },
        { 
          image: ['rag-results.png'],
          info: ['Search results with multiple exercise solutions and navigation']
        }
      ],
      Diagrams: [
        { 
          image: ['rag-architecture.png'],
          info: ['System architecture diagram showing data flow and components']
        }
      ],
      VideoDemo: [
        { 
          video: ['rag-demo.mp4'],
          info: ['Live demonstration of the RAG system in action']
        }
      ]
    },
  },

  // 2. GAN Optimization Research
  {
    id: "gan-optimization",
    folderid: "gan-optimization", 
    projectType: "research",
    platforme: "Machine Learning Research",
    title: "GAN Optimization: Comparative Study of Optimization Algorithms",
    //image: getProjectImages('gan-optimization'),
    category: "AI Research & Computer Vision",
    date: "2024",
    client_for: "Academic Research",
    role: "ML Research Engineer",
    description: "Comprehensive research analyzing the impact of optimization algorithms (Adam, RMSprop, SGD, Lookahead) on GAN training stability and output quality using DCGAN architecture on CIFAR-10 dataset.",
    github_link: "https://github.com/NizarBelaatik/gan-optimization-benchmark",
    research_paper: "#",
    
    technology: ["PyTorch", "Python", "DCGAN", "CIFAR-10"],
    technology_used: {
      'ml_framework': ["PyTorch", "NumPy", "Matplotlib"],
      'architecture': ["DCGAN", "CNN"],
      'optimizers': ["Adam", "RMSprop", "SGD+Momentum", "Lookahead"],
      'evaluation': ["Loss Analysis", "Visual Quality Assessment", "Mode Collapse Detection"]
    },
    
    RoleResp: [{
      Title_1: "ML Research Engineer",
      Data: [
        {
          Title: "Experimental Design",
          Data: [
            "Designed controlled experiments comparing 4 optimization algorithms",
            "Implemented DCGAN architecture with consistent hyperparameters",
            "Developed evaluation metrics for training stability and output quality"
          ]
        },
        {
          Title: "Model Training & Analysis",
          Data: [
            "Trained multiple GAN models with different optimizers",
            "Analyzed loss curves and convergence behavior",
            "Evaluated mode collapse frequency and image diversity"
          ]
        },
        {
          Title: "Research Documentation",
          Data: [
            "Documented findings with quantitative and qualitative analysis",
            "Created visualizations for loss curves and generated samples",
            "Produced practical recommendations for optimizer selection"
          ]
        }
      ],
    }],
    
    KeyFeatures: [{
      Title_1: null,
      Data: [
        {
          Title: "Comprehensive Benchmarking",
          Data: [
            "Compared Adam, RMSprop, SGD+Momentum, and Lookahead optimizers",
            "Quantitative analysis of training stability and convergence",
            "Qualitative assessment of generated image quality and diversity"
          ]
        },
        {
          Title: "Practical Insights",
          Data: [
            "Identified Lookahead as most stable optimizer for GAN training",
            "Provided optimizer selection guidelines for different use cases",
            "Demonstrated trade-offs between convergence speed and stability"
          ]
        },
        {
          Title: "Research Methodology",
          Data: [
            "Controlled experiments with identical architecture and dataset",
            "Both quantitative (loss curves) and qualitative (visual analysis) evaluation",
            "Reproducible experimental setup and code"
          ]
        }
      ],
    }],
    
    VisualsMedia: {
      ScreenShot: [
        { 
          image: ['gan-loss-curves.png'],
          info: ['Comparison of generator and discriminator loss curves across optimizers']
        },
        { 
          image: ['gan-samples.png'],
          info: ['Generated image samples showing evolution across training epochs']
        }
      ],
      Diagrams: [
        { 
          image: ['gan-architecture.png'],
          info: ['DCGAN architecture diagram and experimental setup']
        }
      ]
    },
  },

  // 3. Blockchain Certificate Registry
  {
    id: "blockchain-certificate",
    folderid: "blockchain-certificate",
    projectType: "web",
    platforme: "Decentralized Application (dApp)",
    title: "Blockchain Certificate Registry dApp",
    //image: getProjectImages('blockchain-certificate'),
    category: "Blockchain & Web3",
    date: "2024", 
    client_for: "Personal Project",
    role: "Blockchain Full-Stack Developer",
    description: "A full-stack decentralized application for registering and managing digital certificates on the Ethereum blockchain. Users can register file hashes, transfer ownership, and manage digital assets securely.",
    github_link: "https://github.com/NizarBelaatik/digital-ownership-dapp",
    live_demo: "#",
    
    technology: ["Solidity", "React", "Web3.js", "Truffle", "Ganache"],
    technology_used: {
      'blockchain': ["Solidity", "Ethereum", "Smart Contracts"],
      'front_end': ["React", "Web3.js", "CSS"],
      'back_end': ["Node.js", "Truffle", "Ganache"],
      'tools': ['MetaMask', 'Git']
    },
    
    RoleResp: [{
      Title_1: "Blockchain Full-Stack Developer",
      Data: [
        {
          Title: "Smart Contract Development",
          Data: [
            "Designed and implemented Solidity smart contract for certificate management",
            "Implemented ownership transfer and registration functions",
            "Ensured security best practices and gas optimization"
          ]
        },
        {
          Title: "dApp Frontend",
          Data: [
            "Built React interface for interacting with smart contracts",
            "Integrated Web3.js for blockchain connectivity",
            "Implemented MetaMask integration for user authentication"
          ]
        },
        {
          Title: "Testing & Deployment",
          Data: [
            "Set up local blockchain development with Ganache",
            "Implemented comprehensive testing for smart contracts",
            "Configured Truffle for contract compilation and migration"
          ]
        }
      ],
    }],
    
    KeyFeatures: [{
      Title_1: null,
      Data: [
        {
          Title: "Digital Asset Management",
          Data: [
            "Register files on blockchain using SHA-256 hashes",
            "Transfer ownership of certificates between addresses",
            "View and manage all registered assets"
          ]
        },
        {
          Title: "Blockchain Integration",
          Data: [
            "Smart contract deployment on Ethereum blockchain",
            "MetaMask integration for secure transactions",
            "Real-time blockchain interaction via Web3.js"
          ]
        },
        {
          Title: "User Experience",
          Data: [
            "File upload with automatic hash generation",
            "Ownership transfer with address validation",
            "Asset listing with search and filter capabilities"
          ]
        }
      ],
    }],
    
    VisualsMedia: {
      ScreenShot: [
        { 
          image: ['dapp-dashboard.png'],
          info: ['Main dApp interface showing certificate registration and management']
        },
        { 
          image: ['dapp-transfer.png'],
          info: ['Ownership transfer interface with address validation']
        }
      ],
      Diagrams: [
        { 
          image: ['blockchain-architecture.png'],
          info: ['System architecture showing smart contract and dApp interaction']
        }
      ]
    },
  },

  // ========== YOUR EXISTING PROJECTS ==========
  
  // 4. Integrated Project Management Platform (your existing project1)
  {
    id: "1",
    folderid: "1",
    projectType: "web",
    platforme: "Web Application",
    title: "Integrated Project Management Platform",
    //image: getProjectImages('project1'),
    category: "IGEP",
    date: "September 2023 - February 2024",
    client_for: "Freelance", 
    role: "Full-Stack Developer",
    description: "A comprehensive platform designed to centralize project management tasks, including data collection, processing, and verification. The platform integrates form submission, data management, real-time communication, and role-based access control.",
    github_link: "#",
    
    // ... keep all your existing project1 data exactly as is
    technology: ["Python","Django","RESTful API","HTML","CSS","JavaScript","Jquery","Bootstrap"],
    technology_used: {'front_end': ["HTML","CSS","JavaScript","Jquery","Bootstrap"],
      'back_end': ["Python","Django","RESTful API","JSON"],
      'database': ['SQL',"Postgresql"],
      'techFra': null
    },
    // ... include all your existing RoleResp, KeyFeatures, etc.
  },

  // 5. Student Life Management System (your existing project2)
  {
    id: "2", 
    folderid: "2",
    projectType: "web",
    platforme: "Web Application",
    title: "Student Life Management System",
    //image: getProjectImages('project2'),
    category: "Education Management System",
    date: "February 2023 - June 2023",
    project_for: "Faculte Des science Ben M'Sik",
    client_for: '',
    role: "Full-Stack Developer",
    description: "The Student Life Management System is a web application designed to streamline student interactions with their academic institution. It facilitates the management of various aspects such as scheduling, document requests, and administrative tasks.",
    github_link: "#",
    
    // ... keep all your existing project2 data
    technology: ["JAVA","JEE","HTML","CSS","JavaScript"],
    technology_used: {'front_end': ["HTML","CSS","JavaScript"],
      'back_end': ["JAVA","JEE"],
      'database': ['SQL',"MySql"],
      'techFra': null,
      'tech': ['Apache','XAMPP'],
    },
    // ... include all your existing sections
  },

  // 6. Real-Time Live Chat Application (your existing project3)
  {
    id: "3",
    folderid: "3", 
    projectType: "web",
    platforme: "Web application",
    title: "Real-Time Live Chat Application",
    //image: getProjectImages('project3'),
    category: "Real-time Communication",
    date: "June 2024",
    client_for: "Freelance",
    role: "Full-Stack Developer",
    description: "The Real-Time Live Chat Application is a web-based platform that allows users to engage in single or group chats in real-time. Users can send text messages, images, and files, making it ideal for both casual conversations and professional collaboration.",
    github_link: "#",
    
    // ... keep all your existing project3 data
    technology: ["Python","Django","RESTful API","HTML","CSS","JavaScript","Jquery","Bootstrap"],
    technology_used: {'front_end': ["HTML","CSS","JavaScript","Jquery","Bootstrap"],
      'back_end': ["Python","Django","RESTful API","JSON"],
      'database': ['SQL',"Postgresql"],
      'techFra': ['Git']
    },
    // ... include all your existing sections
  },

  // 7. Twitch TTS Application (your existing project4)
  {
    id: "4",
    folderid: "4",
    projectType: "desk", 
    platforme: "Desktop application",
    title: "Twitch Channel Points TTS (Text-to-Speech)",
    //image: getProjectImages('project4'),
    category: "Software Development",
    date: "May 2020 - June 2020",
    client_for: "Freelance",
    role: "Software Dev",
    description: "Developed a Twitch Channel Points TTS application that allows streamers to convert messages redeemed by viewers using channel points into speech. This enhances audience interaction by giving a voice to viewers during live streams.",
    github_link: "#",
    
    // ... keep all your existing project4 data
    technology: ['Python','PyQt5','Selenium'],
    technology_used: {'Proglang': ['Python','PyQt5'],
      'database': null,
      'frameworks': ['PySide2','Selenium'],
      'Packaging': ['PyInstaller'],
      'techFra': ['Qt Designer','Git','Github']
    },
    // ... include all your existing sections
  },

  // 8. YouTube Downloader (your existing project5)
  {
    id: "5",
    folderid: "5",
    projectType: "desk",
    platforme: "Desktop application", 
    title: "YouTube Video & Music Downloader",
    //image: getProjectImages('project5'),
    category: "Software Development",
    date: "july 2022",
    client_for: "Freelance",
    role: "Software Dev",
    description: "The YouTube Video & Music Downloader is a desktop application that allows users to download videos or music from YouTube. Users can choose between single video downloads or entire playlists, with the option to select from multiple quality choices.",
    github_link: "#",
    
    // ... keep all your existing project5 data
    technology: [ 'Python','PyQt5'],
    technology_used: {'Proglang': ['Python','PyQt5'],
      'database': null,
      'techFra': ['Qt Designer','Git']
    },
    // ... include all your existing sections
  }
];

export default projects_ENG;